### ISSUE TITLE
Unable to use any commands or execute program

### ISSUE THREAD

**Issue by jaygrth** [soundcloud/spdt#8]
![image](https://user-images.githubusercontent.com/20672353/66081211-2f380400-e52d-11e9-88ef-0820c8c58cd7.png)

When trying to use the commands specified in the readme I get this error message. Also, I do not see any of the .jar files that look like should be generated during build.

**Comment by mweiden** [comment]
Have you run `make build`?

**Comment by jaygrth** [comment]
Hi Matt,

I was able to use sbt package to create the jar file. I renamed the jar file from 'spdt-compute_2.12-0.1.0.jar' to 'spdt-compute.jar' and now I am seeing this error: 
![image](https://user-images.githubusercontent.com/20672353/66083639-5cd37c00-e532-11e9-9eee-9b7f0084cca6.png)

**Comment by mweiden** [comment]
Prerequisite: you need [sbt](https://www.scala-sbt.org/) installed.

In the root project directory, first run:
```bash
make build
```

Then run:
```
./bin/spdt --help
```

**Comment by jaygrth** [comment]
Thank you very much Matt. I am relatively new to Scala and sbt.
